#!/bin/bash
set -euo pipefail

###############################################################################
# Run DAG structural quality metrics from a DAG directory.
# Usage: bash scripts/run_dag_metrics.sh [dag_dir] [output_json]
###############################################################################

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
cd "$PROJECT_ROOT"

export PYTHONPATH="${PROJECT_ROOT}:${PYTHONPATH:-}"

DAG_DIR="${1:-data/dag}"
OUTPUT_JSON="${2:-output/eval/dag_metrics_all.json}"
OUTPUT_DIR="$(dirname "$OUTPUT_JSON")"
mkdir -p "$OUTPUT_DIR"

echo "══════════════════════════════════════════"
echo " DAG Structural Quality Evaluation"
echo "══════════════════════════════════════════"
echo "  DAG dir: $DAG_DIR"

python3 -m src.eval.dag_metrics \
  --dag_dir "$DAG_DIR" \
  --output "$OUTPUT_JSON"

echo ""
echo "══════════════════════════════════════════"
echo " DAG metrics saved to: $OUTPUT_JSON"
echo "══════════════════════════════════════════"

python3 - <<'PY'
import json
from pathlib import Path

output_json = Path("output/eval/dag_metrics_all.json")
frag_path = Path("output/eval/structural_metrics_fragment.tex")
if not output_json.exists():
    print("No DAG metrics to export.")
    raise SystemExit(0)

obj = json.loads(output_json.read_text(encoding="utf-8"))
q = obj.get("dag_quality", {})
lines = [
    "% Auto-generated by run_dag_metrics.sh",
    "% Metric & Value \\\\",
    f"AcyclicityRate & {q.get('acyclic_rate', 'TBD'):.4f} \\\\" if isinstance(q.get("acyclic_rate"), (int, float)) else "AcyclicityRate & TBD \\\\",
    f"ConnectedRate & {q.get('connected_rate', 'TBD'):.4f} \\\\" if isinstance(q.get("connected_rate"), (int, float)) else "ConnectedRate & TBD \\\\",
    f"OrphanConclusionRatio & {q.get('orphan_conclusion_ratio', 'TBD'):.4f} \\\\" if isinstance(q.get("orphan_conclusion_ratio"), (int, float)) else "OrphanConclusionRatio & TBD \\\\",
    f"DirectionConsistency & {q.get('direction_consistency', 'TBD'):.4f} \\\\" if isinstance(q.get("direction_consistency"), (int, float)) else "DirectionConsistency & TBD \\\\",
    f"DependencyDepth & {q.get('dependency_depth', 'TBD'):.4f} \\\\" if isinstance(q.get("dependency_depth"), (int, float)) else "DependencyDepth & TBD \\\\",
    f"AvgNodes & {q.get('num_nodes', 'TBD'):.2f} \\\\" if isinstance(q.get("num_nodes"), (int, float)) else "AvgNodes & TBD \\\\",
    f"AvgEdges & {q.get('num_edges', 'TBD'):.2f} \\\\" if isinstance(q.get("num_edges"), (int, float)) else "AvgEdges & TBD \\\\",
]
frag_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
print(f"LaTeX fragment -> {frag_path}")
PY
