#!/bin/bash
set -euo pipefail

###############################################################################
# Run DAG structural quality metrics on model outputs.
# Fills the structural_metrics table in the paper.
#
# Usage: bash scripts/run_dag_metrics.sh [eval_dir]
###############################################################################

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
cd "$PROJECT_ROOT"

export PYTHONPATH="${PROJECT_ROOT}:${PYTHONPATH:-}"

EVAL_DIR="${1:-output/eval}"
OUTPUT="$EVAL_DIR/dag_metrics_all.json"

echo "══════════════════════════════════════════"
echo " DAG Structural Quality Evaluation"
echo "══════════════════════════════════════════"

# Models to evaluate — each entry is "predictions_file:label"
declare -a MODELS=(
    "output/eval/grpo_hierarchical_middle.jsonl:grpo_hierarchical"
    "output/eval/grpo_main_middle.jsonl:grpo_main_linear"
    "output/eval/grpo_outcome_only_middle.jsonl:grpo_outcome_only"
    "output/eval/grpo_no_topo_middle.jsonl:grpo_no_topo"
    "output/eval/grpo_no_continuity_middle.jsonl:grpo_no_continuity"
    "output/eval/sft_middle.jsonl:sft_only"
    "output/eval/distill_7b_compact_middle.jsonl:distill_8b"
)

ALL_RESULTS="[]"

for entry in "${MODELS[@]}"; do
    IFS=':' read -r pred_file label <<< "$entry"

    if [ ! -f "$pred_file" ]; then
        echo "  [SKIP] $label — $pred_file not found"
        continue
    fi

    echo ""
    echo "  [EVAL] $label"

    RESULT=$(python3 -m src.eval.dag_metrics \
        --predictions "$pred_file" \
        --label "$label" \
        2>&1)

    echo "$RESULT"

    # Append to combined results
    METRICS_FILE="$EVAL_DIR/${label}_dag_metrics.json"
    if [ -f "$METRICS_FILE" ]; then
        ALL_RESULTS=$(python3 -c "
import json, sys
existing = json.loads('''$ALL_RESULTS''')
with open('$METRICS_FILE') as f:
    new = json.load(f)
new['model'] = '$label'
existing.append(new)
print(json.dumps(existing))
" 2>/dev/null || echo "$ALL_RESULTS")
    fi
done

# Write combined results
echo "$ALL_RESULTS" | python3 -m json.tool > "$OUTPUT" 2>/dev/null || true

echo ""
echo "══════════════════════════════════════════"
echo " DAG metrics saved to: $OUTPUT"
echo "══════════════════════════════════════════"

# Generate LaTeX fragment for structural_metrics table
python3 -c "
import json
from pathlib import Path

data = json.loads(Path('$OUTPUT').read_text()) if Path('$OUTPUT').exists() else []
if not data:
    print('No DAG metrics to export.')
    exit(0)

lines = ['% Auto-generated by run_dag_metrics.sh']
lines.append('% Model & Acyclicity & Orphan% & Dir-Consist & Avg-Nodes & Avg-Edges \\\\\\\\')
for m in data:
    name = m.get('model', '?')
    acyc = f\"{m.get('acyclicity_rate', 'TBD'):.1f}\" if isinstance(m.get('acyclicity_rate'), (int, float)) else 'TBD'
    orph = f\"{m.get('orphan_ratio', 'TBD'):.2f}\" if isinstance(m.get('orphan_ratio'), (int, float)) else 'TBD'
    dirc = f\"{m.get('direction_consistency', 'TBD'):.2f}\" if isinstance(m.get('direction_consistency'), (int, float)) else 'TBD'
    nodes = f\"{m.get('avg_nodes', 'TBD'):.1f}\" if isinstance(m.get('avg_nodes'), (int, float)) else 'TBD'
    edges = f\"{m.get('avg_edges', 'TBD'):.1f}\" if isinstance(m.get('avg_edges'), (int, float)) else 'TBD'
    lines.append(f'{name} & {acyc} & {orph} & {dirc} & {nodes} & {edges} \\\\\\\\')

Path('$EVAL_DIR/structural_metrics_fragment.tex').write_text('\n'.join(lines) + '\n')
print(f'LaTeX fragment -> $EVAL_DIR/structural_metrics_fragment.tex')
"
